### PR TITLE
Remove sinatra dependency

### PR DESCRIPTION
**Pull request by lihanli**
i'm trying to upgrade roadrunner rails (which uses this gem) to rails 5 but that's blocked by sinatra updating its gemspec to use rack 2.0 (which is required by rails 5) https://github.com/sinatra/sinatra/issues/1135

if we don't require sinatra here then that'll fix the problem

### CODE REVIEW

**Comment by shanear** [comment]
Have you tested this out with a real Rails codebase?

I know the Sinatra dep is janky, but the HTML Code Sniffer library was written in such a way that it doesn't always work by injecting the file into a script tag with JS.

I can't remember the details on exactly what the issue was.

it'd be awesome if this works. Never liked having sinatra in here anyways.

**Comment by lihanli** [comment]
i tested it with roadrunner-rails, i'm not using it in any real projects though.

the acceptance tests here pass and they don't pass if the code sniffer isn't loaded so it seems like it's working

**Comment by lihanli** [comment]
ok i tested it with one of my rails side projects and it works

**Comment by shanear** [comment]
Sweet, just tested it out with our project and it works.

Thanks @lihanli!

🇺🇸 🙇 👍

**Pull request merged**
